model_opts:
  model: PPCI_att
  obs_input_type: [ pose, box,speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: lstm
  backbone: vgg16
exp_opts:
  datasets: [jaad_beh, jaad_all]
  batch_size: [8,8]
  epochs: [40,40]
  lr: [0.0005,0.0005]