model_opts:
  model: PPCIM
  obs_input_type: [ pose, box,speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: lstm
  backbone: vgg16
exp_opts:
  datasets: [  jaad_beh ]
  batch_size: [  8]
  epochs: [  40 ]
  lr: [  0.0005 ]
