model_opts:
  model: PPCI_att_later
  obs_input_type: [ pose, box,speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: lstm
  backbone: vgg16
exp_opts:
  datasets: [pie]
  batch_size: [8]
  epochs: [20]
  lr: [0.0001]
